/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se_BugerKing;

import java.awt.Component;
import java.awt.TextField;
import java.text.SimpleDateFormat;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Faith c.c
 */
public class fr_BugerKing extends javax.swing.JFrame {
//public class fr_BugerKing extends myParentClass{

    /**
     * Creates new form fr_BugerKing
     */
    public fr_BugerKing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sodaSection = new javax.swing.JPanel();
        soda_coke = new javax.swing.JLabel();
        soda_sprite = new javax.swing.JLabel();
        drink_fanta = new javax.swing.JLabel();
        drink_superFloat = new javax.swing.JLabel();
        coke_a = new javax.swing.JTextField();
        sprite_a = new javax.swing.JTextField();
        fanta_a = new javax.swing.JTextField();
        supperFloat_a = new javax.swing.JTextField();
        teaSection = new javax.swing.JPanel();
        tea_iceTea = new javax.swing.JLabel();
        tea_sweetTea = new javax.swing.JLabel();
        tea_water = new javax.swing.JLabel();
        water_a = new javax.swing.JTextField();
        sweetTea_a = new javax.swing.JTextField();
        iceTea_a = new javax.swing.JTextField();
        burgerSection = new javax.swing.JPanel();
        buger_beefBuger = new javax.swing.JLabel();
        buger_chickenBuger = new javax.swing.JLabel();
        Burger_veggieBurger = new javax.swing.JLabel();
        veggieBurger_a = new javax.swing.JTextField();
        doubleWopper_a = new javax.swing.JTextField();
        beefBurger_a = new javax.swing.JTextField();
        chickenBuger_a = new javax.swing.JTextField();
        buger_doubleWopper = new javax.swing.JLabel();
        dessertSection = new javax.swing.JPanel();
        desert_vanillaIcecream = new javax.swing.JLabel();
        vanillaIcecream_a = new javax.swing.JTextField();
        chocolateIcecream_a = new javax.swing.JTextField();
        mangoPudding_a = new javax.swing.JTextField();
        chocoPudding_a = new javax.swing.JTextField();
        desert_chocolateIcecream = new javax.swing.JLabel();
        desert_mangoPudding = new javax.swing.JLabel();
        desert_chocoPudding = new javax.swing.JLabel();
        paySection = new javax.swing.JPanel();
        pay_tax = new javax.swing.JLabel();
        Tax_a = new javax.swing.JTextField();
        subtotal_a = new javax.swing.JTextField();
        totoal_a = new javax.swing.JTextField();
        totaL = new javax.swing.JLabel();
        pay_subtotal = new javax.swing.JLabel();
        dishSection = new javax.swing.JPanel();
        food_rice = new javax.swing.JLabel();
        food_frenchFries = new javax.swing.JLabel();
        food_chicken = new javax.swing.JLabel();
        food_saladBowl = new javax.swing.JLabel();
        saladbowl_a = new javax.swing.JTextField();
        chicken_a = new javax.swing.JTextField();
        frenchFries_a = new javax.swing.JTextField();
        rice_a = new javax.swing.JTextField();
        toppingSection = new javax.swing.JPanel();
        topping_chesse = new javax.swing.JLabel();
        topping_sambal = new javax.swing.JLabel();
        topping_mayo = new javax.swing.JLabel();
        topping_soySauce = new javax.swing.JLabel();
        soySauce_a = new javax.swing.JTextField();
        mayo_a = new javax.swing.JTextField();
        sambal_a = new javax.swing.JTextField();
        chesse_a = new javax.swing.JTextField();
        costSection = new javax.swing.JPanel();
        food_total = new javax.swing.JLabel();
        drink_total = new javax.swing.JLabel();
        orderl_cost = new javax.swing.JLabel();
        food_a = new javax.swing.JTextField();
        drink_a = new javax.swing.JTextField();
        totalcost_a = new javax.swing.JTextField();
        extraSection = new javax.swing.JPanel();
        buger_doubleWopper1 = new javax.swing.JLabel();
        Tip = new javax.swing.JLabel();
        kidsMeal = new javax.swing.JLabel();
        BookTable = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        giftCard_a = new javax.swing.JTextField();
        tip_a = new javax.swing.JTextField();
        kidsMeal_a = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showReceipt = new javax.swing.JTextArea();
        jPanel15 = new javax.swing.JPanel();
        receiptMenu = new javax.swing.JButton();
        resetMenu = new javax.swing.JButton();
        exitMenu = new javax.swing.JButton();
        totalMenu = new javax.swing.JButton();
        sendrOrderMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 2, true));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("BugerKing Self-Service System");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Downloads\\burgerking_logo.png")); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(163, 163, 163)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 100));

        sodaSection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 6, true));

        soda_coke.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        soda_coke.setText("Coke");

        soda_sprite.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        soda_sprite.setText("Sprite");

        drink_fanta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drink_fanta.setText("Fanta");

        drink_superFloat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drink_superFloat.setText("Super Float");

        coke_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        coke_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        coke_a.setText("0");

        sprite_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sprite_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sprite_a.setText("0");

        fanta_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fanta_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fanta_a.setText("0");

        supperFloat_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        supperFloat_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        supperFloat_a.setText("0");

        javax.swing.GroupLayout sodaSectionLayout = new javax.swing.GroupLayout(sodaSection);
        sodaSection.setLayout(sodaSectionLayout);
        sodaSectionLayout.setHorizontalGroup(
            sodaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sodaSectionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(sodaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sodaSectionLayout.createSequentialGroup()
                        .addComponent(drink_superFloat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(supperFloat_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sodaSectionLayout.createSequentialGroup()
                        .addComponent(soda_sprite, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sprite_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sodaSectionLayout.createSequentialGroup()
                        .addComponent(drink_fanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(fanta_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sodaSectionLayout.createSequentialGroup()
                        .addComponent(soda_coke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(coke_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        sodaSectionLayout.setVerticalGroup(
            sodaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sodaSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sodaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(soda_coke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coke_a, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(sodaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sprite_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soda_sprite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sodaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fanta_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drink_fanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sodaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supperFloat_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drink_superFloat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(sodaSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 300, 190));

        teaSection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 6, true));

        tea_iceTea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tea_iceTea.setText("Ice Tea");

        tea_sweetTea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tea_sweetTea.setText("Sweet Tea");

        tea_water.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tea_water.setText("Water");

        water_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        water_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        water_a.setText("0");

        sweetTea_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sweetTea_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sweetTea_a.setText("0");

        iceTea_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        iceTea_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iceTea_a.setText("0");

        javax.swing.GroupLayout teaSectionLayout = new javax.swing.GroupLayout(teaSection);
        teaSection.setLayout(teaSectionLayout);
        teaSectionLayout.setHorizontalGroup(
            teaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teaSectionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(teaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teaSectionLayout.createSequentialGroup()
                        .addComponent(tea_iceTea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(iceTea_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teaSectionLayout.createSequentialGroup()
                        .addGroup(teaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tea_water, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tea_sweetTea, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(teaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sweetTea_a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(water_a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        teaSectionLayout.setVerticalGroup(
            teaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teaSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tea_iceTea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iceTea_a, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(teaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sweetTea_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tea_sweetTea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(teaSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(water_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tea_water, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );

        getContentPane().add(teaSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 320, 150));

        burgerSection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 6, true));

        buger_beefBuger.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buger_beefBuger.setText("Beef Burger");

        buger_chickenBuger.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buger_chickenBuger.setText("Chicken burger");

        Burger_veggieBurger.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Burger_veggieBurger.setText("Veggie Burger");

        veggieBurger_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        veggieBurger_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        veggieBurger_a.setText("0");

        doubleWopper_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        doubleWopper_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        doubleWopper_a.setText("0");

        beefBurger_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        beefBurger_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        beefBurger_a.setText("0");

        chickenBuger_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chickenBuger_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chickenBuger_a.setText("0");

        buger_doubleWopper.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buger_doubleWopper.setText("Double Wopper");

        javax.swing.GroupLayout burgerSectionLayout = new javax.swing.GroupLayout(burgerSection);
        burgerSection.setLayout(burgerSectionLayout);
        burgerSectionLayout.setHorizontalGroup(
            burgerSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(burgerSectionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(burgerSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, burgerSectionLayout.createSequentialGroup()
                        .addComponent(Burger_veggieBurger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(veggieBurger_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(burgerSectionLayout.createSequentialGroup()
                        .addComponent(buger_chickenBuger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(chickenBuger_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, burgerSectionLayout.createSequentialGroup()
                        .addGroup(burgerSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buger_beefBuger, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(buger_doubleWopper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(burgerSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beefBurger_a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doubleWopper_a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        burgerSectionLayout.setVerticalGroup(
            burgerSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(burgerSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(burgerSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chickenBuger_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buger_chickenBuger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(burgerSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beefBurger_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buger_beefBuger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(burgerSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doubleWopper_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buger_doubleWopper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(burgerSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(veggieBurger_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Burger_veggieBurger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(burgerSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 300, 190));

        dessertSection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 6, true));

        desert_vanillaIcecream.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        desert_vanillaIcecream.setText("Vanilla Icecream");

        vanillaIcecream_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vanillaIcecream_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vanillaIcecream_a.setText("0");

        chocolateIcecream_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chocolateIcecream_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chocolateIcecream_a.setText("0");

        mangoPudding_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mangoPudding_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mangoPudding_a.setText("0");

        chocoPudding_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chocoPudding_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chocoPudding_a.setText("0");

        desert_chocolateIcecream.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        desert_chocolateIcecream.setText("Chocolate Icecream");

        desert_mangoPudding.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        desert_mangoPudding.setText("Mango Pudding");

        desert_chocoPudding.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        desert_chocoPudding.setText("Choco Pudding");

        javax.swing.GroupLayout dessertSectionLayout = new javax.swing.GroupLayout(dessertSection);
        dessertSection.setLayout(dessertSectionLayout);
        dessertSectionLayout.setHorizontalGroup(
            dessertSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dessertSectionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(dessertSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dessertSectionLayout.createSequentialGroup()
                        .addComponent(desert_chocoPudding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(chocoPudding_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dessertSectionLayout.createSequentialGroup()
                        .addComponent(desert_chocolateIcecream, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(chocolateIcecream_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dessertSectionLayout.createSequentialGroup()
                        .addComponent(desert_mangoPudding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(mangoPudding_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dessertSectionLayout.createSequentialGroup()
                        .addComponent(desert_vanillaIcecream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(vanillaIcecream_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dessertSectionLayout.setVerticalGroup(
            dessertSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dessertSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dessertSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(desert_vanillaIcecream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vanillaIcecream_a, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(dessertSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chocolateIcecream_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desert_chocolateIcecream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dessertSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mangoPudding_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desert_mangoPudding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dessertSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chocoPudding_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desert_chocoPudding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(dessertSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 300, 190));

        paySection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 6, true));

        pay_tax.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pay_tax.setText("Tax");

        Tax_a.setEditable(false);
        Tax_a.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tax_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tax_a.setText("0");
        Tax_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tax_aActionPerformed(evt);
            }
        });

        subtotal_a.setEditable(false);
        subtotal_a.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subtotal_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        subtotal_a.setText("0");
        subtotal_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotal_aActionPerformed(evt);
            }
        });

        totoal_a.setEditable(false);
        totoal_a.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totoal_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totoal_a.setText("0");
        totoal_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totoal_aActionPerformed(evt);
            }
        });

        totaL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totaL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totaL.setText("Total");

        pay_subtotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pay_subtotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pay_subtotal.setText("Sub Total");

        javax.swing.GroupLayout paySectionLayout = new javax.swing.GroupLayout(paySection);
        paySection.setLayout(paySectionLayout);
        paySectionLayout.setHorizontalGroup(
            paySectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paySectionLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(paySectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paySectionLayout.createSequentialGroup()
                        .addGroup(paySectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pay_subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(paySectionLayout.createSequentialGroup()
                        .addComponent(pay_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addGroup(paySectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paySectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(subtotal_a, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(totoal_a))
                    .addComponent(Tax_a, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        paySectionLayout.setVerticalGroup(
            paySectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paySectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paySectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paySectionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Tax_a, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pay_tax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paySectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotal_a, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paySectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totoal_a, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        getContentPane().add(paySection, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 300, 150));

        dishSection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 6, true));

        food_rice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        food_rice.setText("Rice");

        food_frenchFries.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        food_frenchFries.setText("French Fries");

        food_chicken.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        food_chicken.setText("Chicken");

        food_saladBowl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        food_saladBowl.setText("Salad Bowl");

        saladbowl_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saladbowl_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        saladbowl_a.setText("0");

        chicken_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chicken_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chicken_a.setText("0");

        frenchFries_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        frenchFries_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        frenchFries_a.setText("0");

        rice_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rice_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rice_a.setText("0");
        rice_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rice_aActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dishSectionLayout = new javax.swing.GroupLayout(dishSection);
        dishSection.setLayout(dishSectionLayout);
        dishSectionLayout.setHorizontalGroup(
            dishSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dishSectionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(dishSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dishSectionLayout.createSequentialGroup()
                        .addComponent(food_saladBowl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(saladbowl_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dishSectionLayout.createSequentialGroup()
                        .addComponent(food_rice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rice_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dishSectionLayout.createSequentialGroup()
                        .addGroup(dishSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(food_chicken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(food_frenchFries, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(dishSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frenchFries_a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chicken_a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        dishSectionLayout.setVerticalGroup(
            dishSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dishSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dishSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(food_rice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rice_a, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(dishSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frenchFries_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(food_frenchFries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dishSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chicken_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(food_chicken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dishSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saladbowl_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(food_saladBowl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(dishSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 320, 190));

        toppingSection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 6, true));

        topping_chesse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        topping_chesse.setText("Chesse");

        topping_sambal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        topping_sambal.setText("Sambal");

        topping_mayo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        topping_mayo.setText("Mayo");

        topping_soySauce.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        topping_soySauce.setText("Soy Sauce");

        soySauce_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        soySauce_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        soySauce_a.setText("0");

        mayo_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mayo_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mayo_a.setText("0");

        sambal_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sambal_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sambal_a.setText("0");

        chesse_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chesse_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chesse_a.setText("0");
        chesse_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chesse_aActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toppingSectionLayout = new javax.swing.GroupLayout(toppingSection);
        toppingSection.setLayout(toppingSectionLayout);
        toppingSectionLayout.setHorizontalGroup(
            toppingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppingSectionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(toppingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppingSectionLayout.createSequentialGroup()
                        .addComponent(topping_soySauce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(soySauce_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toppingSectionLayout.createSequentialGroup()
                        .addComponent(topping_chesse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(chesse_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppingSectionLayout.createSequentialGroup()
                        .addGroup(toppingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(topping_mayo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(topping_sambal, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(toppingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sambal_a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mayo_a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        toppingSectionLayout.setVerticalGroup(
            toppingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppingSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toppingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(topping_chesse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chesse_a, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(toppingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sambal_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topping_sambal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(toppingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mayo_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topping_mayo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(toppingSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soySauce_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topping_soySauce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(toppingSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 320, 190));

        costSection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 6, true));

        food_total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        food_total.setText("Meal Total");

        drink_total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drink_total.setText("Drink Total");

        orderl_cost.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orderl_cost.setText("Order Cost");

        food_a.setEditable(false);
        food_a.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        food_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        food_a.setText("0");
        food_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food_aActionPerformed(evt);
            }
        });

        drink_a.setEditable(false);
        drink_a.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        drink_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        drink_a.setText("0");

        totalcost_a.setEditable(false);
        totalcost_a.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalcost_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalcost_a.setText("0");
        totalcost_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalcost_aActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout costSectionLayout = new javax.swing.GroupLayout(costSection);
        costSection.setLayout(costSectionLayout);
        costSectionLayout.setHorizontalGroup(
            costSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costSectionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(costSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(costSectionLayout.createSequentialGroup()
                        .addComponent(drink_total, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(costSectionLayout.createSequentialGroup()
                        .addGroup(costSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(food_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orderl_cost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(costSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalcost_a, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(drink_a, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(food_a))
                .addGap(27, 27, 27))
        );
        costSectionLayout.setVerticalGroup(
            costSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(costSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(food_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(food_a, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(costSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drink_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drink_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(costSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalcost_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderl_cost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );

        getContentPane().add(costSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 300, 150));

        extraSection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 6, true));

        buger_doubleWopper1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buger_doubleWopper1.setText("Buy Giftcard");

        Tip.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tip.setText("Tip");

        kidsMeal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kidsMeal.setText("kids Meal");

        BookTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BookTable.setText("Reserve Table");

        jTextField27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField27.setText("0");

        giftCard_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        giftCard_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        giftCard_a.setText("0");

        tip_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tip_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tip_a.setText("0");

        kidsMeal_a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kidsMeal_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kidsMeal_a.setText("0");

        javax.swing.GroupLayout extraSectionLayout = new javax.swing.GroupLayout(extraSection);
        extraSection.setLayout(extraSectionLayout);
        extraSectionLayout.setHorizontalGroup(
            extraSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extraSectionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(extraSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, extraSectionLayout.createSequentialGroup()
                        .addComponent(BookTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(extraSectionLayout.createSequentialGroup()
                        .addComponent(kidsMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(kidsMeal_a, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, extraSectionLayout.createSequentialGroup()
                        .addGroup(extraSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tip, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(buger_doubleWopper1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(extraSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tip_a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giftCard_a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        extraSectionLayout.setVerticalGroup(
            extraSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extraSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(extraSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kidsMeal_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kidsMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(extraSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tip_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(extraSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giftCard_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buger_doubleWopper1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(extraSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(extraSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 300, 190));

        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 6, true));

        showReceipt.setEditable(false);
        showReceipt.setColumns(20);
        showReceipt.setRows(5);
        jScrollPane1.setViewportView(showReceipt);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 110, 250, 610));

        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 6, true));

        receiptMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        receiptMenu.setText("Receipt");
        receiptMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptMenuActionPerformed(evt);
            }
        });

        resetMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resetMenu.setText("Reset");
        resetMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetMenuActionPerformed(evt);
            }
        });

        exitMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });

        totalMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalMenu.setText("Total");
        totalMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalMenuActionPerformed(evt);
            }
        });

        sendrOrderMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sendrOrderMenu.setText("Send Order ");
        sendrOrderMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendrOrderMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(totalMenu)
                .addGap(88, 88, 88)
                .addComponent(receiptMenu)
                .addGap(97, 97, 97)
                .addComponent(resetMenu)
                .addGap(119, 119, 119)
                .addComponent(sendrOrderMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(110, 110, 110)
                .addComponent(exitMenu)
                .addGap(100, 100, 100))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptMenu)
                    .addComponent(resetMenu)
                    .addComponent(exitMenu)
                    .addComponent(totalMenu)
                    .addComponent(sendrOrderMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 940, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void receiptMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptMenuActionPerformed
        // TODO add your handling code here:
        int referenceCode = 23019 + (int) (Math.random()*60106);
        
                   showReceipt.append("\nBURGER KING SELF-SERVICE SYSTEM:\n" +
                                "ReferenceCode:\t" + referenceCode +
                        "\n===============================\n" + 
                                   "Meal:\t" + food_a.getText() + "\n\n" +
                                   "Drink:\t" + drink_a.getText() + "\n\n" +
                                "Total cost of order:\t" + totalcost_a.getText() + "\n\n" + 
                        "\n===============================\n" +
                        "Tax:\t" + Tax_a.getText() + "\n\n" +
                            "Subtotal:\t" + subtotal_a.getText() + "\n\n" +
                        "Total:\t" + totoal_a.getText() + "\n\n" +
                        "\n===============================\n" +
                        "\n\ntThanks for eating with us"
                                + " hope to see you Again");
                        
    }//GEN-LAST:event_receiptMenuActionPerformed

    private void Tax_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tax_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tax_aActionPerformed

    private void subtotal_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotal_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotal_aActionPerformed

    private void totoal_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totoal_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totoal_aActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        // TODO add your handling code here:
        myChildClass iExit = new myChildClass();
        iExit.iexitButton();
    }//GEN-LAST:event_exitMenuActionPerformed


    private void resetMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetMenuActionPerformed
        // TODO add your handling code here:
        showReceipt.setText("00");
//        iceTea_a.setText("");
        JTextField cleartext = null;
       
       // Reset user interface
         Component[] component1 = dessertSection.getComponents();
        for (int i = 0; i < component1.length; i++) {
            
            if (component1[i] instanceof JTextField) {
                JTextField textfield = (JTextField) component1[i];
                //button.setEnabled(true);
                textfield.setText("0");
            }
        }
        
        Component[] component2 = sodaSection.getComponents();
        for (int i = 0; i < component2.length; i++) {
            
            if (component2[i] instanceof JTextField) {
                JTextField textfield = (JTextField) component2[i];
                //button.setEnabled(true);
                textfield.setText("0");
            }
        }
         Component[] component3 = teaSection.getComponents();
        for (int i = 0; i < component3.length; i++) {
            
            if (component3[i] instanceof JTextField) {
                JTextField textfield = (JTextField) component3[i];
                //button.setEnabled(true);
                textfield.setText("0");
            }
        }
         Component[] component4 = toppingSection.getComponents();
        for (int i = 0; i < component4.length; i++) {
            
            if (component4[i] instanceof JTextField) {
                JTextField textfield = (JTextField) component4[i];
                //button.setEnabled(true);
                textfield.setText("0");
            }
        }
         Component[] component5 = burgerSection.getComponents();
        for (int i = 0; i < component5.length; i++) {
            
            if (component5[i] instanceof JTextField) {
                JTextField textfield = (JTextField) component5[i];
                //button.setEnabled(true);
                textfield.setText("0");
            }
        }
         Component[] component6 = dishSection.getComponents();
        for (int i = 0; i < component6.length; i++) {
            
            if (component6[i] instanceof JTextField) {
                JTextField textfield = (JTextField) component6[i];
                //button.setEnabled(true);
                textfield.setText("0");
            }
        }
         Component[] component7 = extraSection.getComponents();
        for (int i = 0; i < component7.length; i++) {
            
            if (component7[i] instanceof JTextField) {
                JTextField textfield = (JTextField) component7[i];
                //button.setEnabled(true);
                textfield.setText("0");
            }
        }
          Component[] component8 = paySection.getComponents();
        for (int i = 0; i < component8.length; i++) {
            
            if (component8[i] instanceof JTextField) {
                JTextField textfield = (JTextField) component8[i];
                //button.setEnabled(true);
                textfield.setText("0");
            }
        }
          Component[] component9 = costSection.getComponents();
        for (int i = 0; i < component9.length; i++) {
            
            if (component9[i] instanceof JTextField) {
                JTextField textfield = (JTextField) component9[i];
                //button.setEnabled(true);
                textfield.setText("0");
            }
        }      

    }//GEN-LAST:event_resetMenuActionPerformed

    /*
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException,
            InstantiationException, IllegalAccessException,
            UnsupportedLookAndFeelException,
            java.lang.ClassNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_BugerKing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_BugerKing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_BugerKing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_BugerKing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_BugerKing().setVisible(true);
            }
        });
    }

    private void sendrOrderMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendrOrderMenuActionPerformed
        // TODO add your handling code here:
        myChildClass iSendOrder = new myChildClass();
        iSendOrder.isendOrderButton();
    }//GEN-LAST:event_sendrOrderMenuActionPerformed

    private void totalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalMenuActionPerformed
        // TODO add your handling code here:
        myChildClass itemCost = new myChildClass();
        double isubtotal, itotal, itax;

        itemCost.kidsMeal = itemCost.kidsMeal_p * Double.parseDouble(kidsMeal_a.getText());
        itemCost.beefBurger = itemCost.beefBurger_p * Double.parseDouble(beefBurger_a.getText());
        itemCost.rice = itemCost.rice_p * Double.parseDouble(rice_a.getText());
        itemCost.frenchFries = itemCost.frenchFries_p * Double.parseDouble(frenchFries_a.getText());
        itemCost.chicken = itemCost.chicken_p * Double.parseDouble(chicken_a.getText());
        itemCost.saladbowl = itemCost.saladbowl_p * Double.parseDouble(saladbowl_a.getText());
        itemCost.chickenBuger = itemCost.chickenBuger_p * Double.parseDouble(chickenBuger_a.getText());
        itemCost.doubleWopper = itemCost.doubleWopper_p * Double.parseDouble(doubleWopper_a.getText());
        itemCost.veggieBurger = itemCost.veggieBurger_p * Double.parseDouble(veggieBurger_a.getText());
        itemCost.chesse = itemCost.chesse_p * Double.parseDouble(chesse_a.getText());
        itemCost.sambal = itemCost.sambal_p * Double.parseDouble(sambal_a.getText());
        itemCost.mayo = itemCost.mayo_p * Double.parseDouble(mayo_a.getText());
        itemCost.soySauce = itemCost.soySauce_p * Double.parseDouble(soySauce_a.getText());
        itemCost.fanta = itemCost.fanta_p * Double.parseDouble(fanta_a.getText());
        itemCost.coke = itemCost.coke_p * Double.parseDouble(coke_a.getText());
        itemCost.sprite = itemCost.sprite_p * Double.parseDouble(sprite_a.getText());
        itemCost.supperFloat = itemCost.supperFloat_p * Double.parseDouble(supperFloat_a.getText());
        itemCost.chocolateIcecream = itemCost.chocolateIcecream_p * Double.parseDouble(chocolateIcecream_a.getText());
        itemCost.vanillaIcecream = itemCost.vanillaIcecream_p * Double.parseDouble(vanillaIcecream_a.getText());
        itemCost.mangoPudding = itemCost.mangoPudding_p * Double.parseDouble(mangoPudding_a.getText());
        itemCost.chocoPudding = itemCost.chocoPudding_p * Double.parseDouble(chocoPudding_a.getText());
        itemCost.iceTea = itemCost.iceTea_p * Double.parseDouble(iceTea_a.getText());
        itemCost.sweetTea = itemCost.sweetTea_p * Double.parseDouble(sweetTea_a.getText());
        itemCost.water = itemCost.water_p * Double.parseDouble(water_a.getText());
        itemCost.tip = itemCost.tip_p * Double.parseDouble(tip_a.getText());
        itemCost.giftCard = itemCost.giftCard_p * Double.parseDouble(giftCard_a.getText());
        itemCost.Tax = itemCost.Tax_p * Double.parseDouble(Tax_a.getText());
        itemCost.food = itemCost.food_p * Double.parseDouble(food_a.getText());
        itemCost.drink = itemCost.drink_p * Double.parseDouble(drink_a.getText());
        itemCost.totalcost = itemCost.totalcost_p * Double.parseDouble(totalcost_a.getText());
        isubtotal = itemCost.GetPrice();
        itax = itemCost.calculateTax(isubtotal);
        itotal = isubtotal + itax;

        String Subtotal = String.format("Rp%.2f", isubtotal);
        subtotal_a.setText(Subtotal);

        String total = String.format("Rp%.2f", itotal);
        totoal_a.setText(total);

        String taX = String.format("Rp%.2f", itax);
        Tax_a.setText(taX);
        
        String ifood = String.format("Rp%.2f", itemCost.food_p);
        food_a.setText(ifood);

        String idrink = String.format("Rp%.2f", itemCost.drink_p);
        drink_a.setText(idrink);

        String itotalcost = String.format("Rp%.2f", itemCost.totalcost_p);
        totalcost_a.setText(itotalcost);
    }//GEN-LAST:event_totalMenuActionPerformed

    private void rice_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rice_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rice_aActionPerformed

    private void chesse_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chesse_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chesse_aActionPerformed

    private void totalcost_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalcost_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalcost_aActionPerformed

    private void food_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_food_aActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookTable;
    private javax.swing.JLabel Burger_veggieBurger;
    private javax.swing.JTextField Tax_a;
    private javax.swing.JLabel Tip;
    private javax.swing.JTextField beefBurger_a;
    private javax.swing.JLabel buger_beefBuger;
    private javax.swing.JLabel buger_chickenBuger;
    private javax.swing.JLabel buger_doubleWopper;
    private javax.swing.JLabel buger_doubleWopper1;
    private javax.swing.JPanel burgerSection;
    private javax.swing.JTextField chesse_a;
    private javax.swing.JTextField chickenBuger_a;
    private javax.swing.JTextField chicken_a;
    private javax.swing.JTextField chocoPudding_a;
    private javax.swing.JTextField chocolateIcecream_a;
    private javax.swing.JTextField coke_a;
    private javax.swing.JPanel costSection;
    private javax.swing.JLabel desert_chocoPudding;
    private javax.swing.JLabel desert_chocolateIcecream;
    private javax.swing.JLabel desert_mangoPudding;
    private javax.swing.JLabel desert_vanillaIcecream;
    private javax.swing.JPanel dessertSection;
    private javax.swing.JPanel dishSection;
    private javax.swing.JTextField doubleWopper_a;
    private javax.swing.JTextField drink_a;
    private javax.swing.JLabel drink_fanta;
    private javax.swing.JLabel drink_superFloat;
    private javax.swing.JLabel drink_total;
    private javax.swing.JButton exitMenu;
    private javax.swing.JPanel extraSection;
    private javax.swing.JTextField fanta_a;
    private javax.swing.JTextField food_a;
    private javax.swing.JLabel food_chicken;
    private javax.swing.JLabel food_frenchFries;
    private javax.swing.JLabel food_rice;
    private javax.swing.JLabel food_saladBowl;
    private javax.swing.JLabel food_total;
    private javax.swing.JTextField frenchFries_a;
    private javax.swing.JTextField giftCard_a;
    private javax.swing.JTextField iceTea_a;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JLabel kidsMeal;
    private javax.swing.JTextField kidsMeal_a;
    private javax.swing.JTextField mangoPudding_a;
    private javax.swing.JTextField mayo_a;
    private javax.swing.JLabel orderl_cost;
    private javax.swing.JPanel paySection;
    private javax.swing.JLabel pay_subtotal;
    private javax.swing.JLabel pay_tax;
    private javax.swing.JButton receiptMenu;
    private javax.swing.JButton resetMenu;
    private javax.swing.JTextField rice_a;
    private javax.swing.JTextField saladbowl_a;
    private javax.swing.JTextField sambal_a;
    private javax.swing.JButton sendrOrderMenu;
    private javax.swing.JTextArea showReceipt;
    private javax.swing.JPanel sodaSection;
    private javax.swing.JLabel soda_coke;
    private javax.swing.JLabel soda_sprite;
    private javax.swing.JTextField soySauce_a;
    private javax.swing.JTextField sprite_a;
    private javax.swing.JTextField subtotal_a;
    private javax.swing.JTextField supperFloat_a;
    private javax.swing.JTextField sweetTea_a;
    private javax.swing.JPanel teaSection;
    private javax.swing.JLabel tea_iceTea;
    private javax.swing.JLabel tea_sweetTea;
    private javax.swing.JLabel tea_water;
    private javax.swing.JTextField tip_a;
    private javax.swing.JPanel toppingSection;
    private javax.swing.JLabel topping_chesse;
    private javax.swing.JLabel topping_mayo;
    private javax.swing.JLabel topping_sambal;
    private javax.swing.JLabel topping_soySauce;
    private javax.swing.JLabel totaL;
    private javax.swing.JButton totalMenu;
    private javax.swing.JTextField totalcost_a;
    private javax.swing.JTextField totoal_a;
    private javax.swing.JTextField vanillaIcecream_a;
    private javax.swing.JTextField veggieBurger_a;
    private javax.swing.JTextField water_a;
    // End of variables declaration//GEN-END:variables

}
